export const SEED_CARDS = [
  {
    name: '3rd Year 2026-27',
    description: 'Master academic sheets, attendance reports, student data, timetable, and LDP/LeetCode trackers.',
    icon: 'GraduationCap',
    color: 'emerald',
    category: 'Academic',
    order: 0,
    items: [
      {
        name: 'Student Data & Master Sheets',
        description: 'Master student lists, mentor details, and batch directories.',
        resourceUrl: 'https://docs.google.com/spreadsheets/d/1_L1320CCq714iPMoXsxVIsFnK9jeYK-SOxhGtoEOppE/edit?gid=470107062#gid=470107062',
        order: 0,
        resources: [
          {
            name: 'Final-BridgeLabz 3Y (5thSem) ODD 2026-27 Student Data',
            description: 'Final student master data sheet',
            url: 'https://docs.google.com/spreadsheets/d/1_L1320CCq714iPMoXsxVIsFnK9jeYK-SOxhGtoEOppE/edit?gid=470107062#gid=470107062',
            emailsUsed: [],
          },
          {
            name: 'BridgeLabz 3Y (5thSem) ODD 2026-27 Student Data',
            description: '5th Semester odd student database',
            url: 'https://docs.google.com/spreadsheets/d/1rKBzHU5c82NTmX8f5FGFtlRTOkQu0tGNagnTpU5nDog/edit?gid=19039436#gid=19039436',
            emailsUsed: [],
          },
          {
            name: 'Updated 3rd Yr Students Data',
            description: 'Updated student records and details',
            url: 'https://docs.google.com/spreadsheets/d/1bM0EmQMPf0eVlQFQnL20xzbytVbHA7zSnziTav-ym0g/edit?gid=877237483#gid=877237483',
            emailsUsed: [],
          },
          {
            name: 'BL Mentors details for GLA',
            description: 'GLA mentor contact details & allocations',
            url: 'https://docs.google.com/spreadsheets/d/1iMGQfQ_92WlkbUhcwkE-xTzLzq66PwLgTOP4ndfwpEw/edit?gid=1164337446#gid=1164337446',
            emailsUsed: [],
          },
          {
            name: 'Student Data from GLA (Folder)',
            description: 'Google Drive folder containing GLA student documents',
            url: 'https://drive.google.com/drive/folders/1e186lFanCbrAWeIOu3qWzBqsylZ93PHV',
            emailsUsed: [],
          },
          {
            name: '3rd Yr Drive Folder',
            description: 'Google Drive root directory for 3rd Year',
            url: 'https://drive.google.com/drive/folders/1OatdWYRca5uz-UKsbJUG-e26Obfkj0fD',
            emailsUsed: [],
          },
        ],
      },
      {
        name: 'Attendance Reports',
        description: 'Weekly and monthly attendance tracking registers.',
        resourceUrl: 'https://docs.google.com/spreadsheets/d/1NChIEeXJ68Wbb1M9XAcQBkbbcaKMwd87I9a6UDk3vN4/edit?gid=564338563#gid=564338563',
        order: 1,
        resources: [
          {
            name: 'Attendence PORTAL',
            description: 'Main Attendance Portal Sheet',
            url: 'https://docs.google.com/spreadsheets/d/1NChIEeXJ68Wbb1M9XAcQBkbbcaKMwd87I9a6UDk3vN4/edit?gid=564338563#gid=564338563',
            emailsUsed: [],
          },
          {
            name: '1st Week Attendance Report (26th Aug - 28th Aug)',
            description: '5th Sem 1st Week Attendance',
            url: 'https://docs.google.com/spreadsheets/d/11GzkNDZzGxv0Oa0bO4HK8lwlZXdpkWLrRQvKkWgGZ04/edit?gid=165933560#gid=165933560',
            emailsUsed: [],
          },
          {
            name: '3rd Week Attendance Report (17th Aug - 21st Aug)',
            description: '5th Sem 3rd Week Attendance',
            url: 'https://docs.google.com/spreadsheets/d/1XT2BGEmJnkwPCBybllV1CQHO50VxuGmYmf2RjTjqPeE/edit?gid=1952843545#gid=1952843545',
            emailsUsed: [],
          },
          {
            name: '2nd Week Attendance Report (10th Aug - 14th Aug)',
            description: '5th Sem 2nd Week Attendance',
            url: 'https://docs.google.com/spreadsheets/d/1BE170NNXMuUMiLoLs_aq-LoPDwLXRif2cjBMvYQUf24/edit?gid=1511890621#gid=1511890621',
            emailsUsed: [],
          },
          {
            name: '1st Week Attendance Report (3rd Aug - 7th Aug)',
            description: '5th Sem Initial Attendance Report',
            url: 'https://docs.google.com/spreadsheets/d/1ChrNCPEEcIe1UjjQqqdLhyI5BA4rFHPwM1BkDk75UHM/edit?gid=796791540#gid=796791540',
            emailsUsed: [],
          },
        ],
      },
      {
        name: 'Trackers & Learning (LDP, LeetCode, GitHub)',
        description: 'Student problem solving, GitHub profile collections, and LDP progress.',
        resourceUrl: 'https://docs.google.com/spreadsheets/d/1FIsTRJXq7LV9-SHqXZynEE4UA5MLf4ruYDuDBX8cjH8/edit?gid=1198022520#gid=1198022520',
        order: 2,
        resources: [
          {
            name: '1. GLA 2026-27 LDP Tracker - Odd Semester',
            description: 'Odd semester LDP learning tracker',
            url: 'https://docs.google.com/spreadsheets/d/1FIsTRJXq7LV9-SHqXZynEE4UA5MLf4ruYDuDBX8cjH8/edit?gid=1198022520#gid=1198022520',
            emailsUsed: [],
          },
          {
            name: '2. GLA 2026-27 LeetCode & GitHub Tracker - 5th Semester',
            description: '5th Semester LeetCode & GitHub progress sheet',
            url: 'https://docs.google.com/spreadsheets/d/1XqXBnh4ts9rHcaLC1FB5jTTU36TVAU2gobcI0bDkfOs/edit?gid=919919736#gid=919919736',
            emailsUsed: [],
          },
          {
            name: '3rd Yr LeetCode tracker',
            description: 'Overall LeetCode solved problems tracking sheet',
            url: 'https://docs.google.com/spreadsheets/d/1NwB7BxX4Hgp7LNDqn2q-oNnau75tvCLna25hXFv340s/edit?gid=0#gid=0',
            emailsUsed: [],
          },
          {
            name: '3Y Section wise LeetCode problems covered',
            description: 'Section wise breakdown of covered DSA topics',
            url: 'https://docs.google.com/spreadsheets/d/12cBQeugKVfdsPlW628NYW9lzhLLgPozfQ9crpfsxx2U/edit?pli=1&gid=674299685#gid=674299685',
            emailsUsed: [],
          },
          {
            name: 'LeetCode-Tracking guidelines for Mentors',
            description: 'Mentor evaluation and tracking guidelines document',
            url: 'https://docs.google.com/document/d/1C9EtFpJiZHn-_uerqkqMU5yjEKC-j585BsipRq19XDY/edit?tab=t.0#heading=h.3kdt8s6u25fy',
            emailsUsed: [],
          },
          {
            name: 'GLA 2026–27 3rd Year LeetCode & GitHub Profile Collection (Form)',
            description: 'Student profile submission Google Form',
            url: 'https://docs.google.com/forms/d/e/1FAIpQLSeIPPzVXvgBy6v0z3V_oap323MA7xbVbhTzFZQxKCdQ3jqKVA/viewform?fbzx=-6153289744527019907',
            emailsUsed: [],
          },
          {
            name: 'GLA 2026–27 Profile Collection Responses',
            description: 'Responses spreadsheet for profile collection form',
            url: 'https://docs.google.com/spreadsheets/d/1xK8X5Kdfh00lYSYrZJUWa_mE2NcR2Vqq_Q4Qdmel96I/edit?resourcekey=&gid=58920771#gid=58920771',
            emailsUsed: [],
          },
        ],
      },
      {
        name: 'Timetables & Classroom',
        description: 'Faculty time tables, class schedules, and Google Classroom link.',
        resourceUrl: 'https://docs.google.com/spreadsheets/d/11VQgJToumWmCHJKrGL5XnpZ-ms8p5wMCUi2qJRYIHnY/edit?gid=0#gid=0',
        order: 3,
        resources: [
          {
            name: '3Y TT (TimeTable)',
            description: '3rd Year class timetable sheet',
            url: 'https://docs.google.com/spreadsheets/d/11VQgJToumWmCHJKrGL5XnpZ-ms8p5wMCUi2qJRYIHnY/edit?gid=0#gid=0',
            emailsUsed: [],
          },
          {
            name: 'Copy of Odd Sem Faculty & Class Time Table 2026-27',
            description: 'Faculty allotment & lecture schedules',
            url: 'https://docs.google.com/spreadsheets/d/1E_rWyQ1H4-vXp8XME48_v2qg0D9ORzPG/edit?gid=59355118#gid=59355118',
            emailsUsed: [],
          },
          {
            name: 'Google Classroom - All Topics',
            description: 'Classroom portal for assignments and announcements',
            url: 'https://classroom.google.com/w/Nzk0OTEyNTQyOTQz/t/all',
            emailsUsed: [],
          },
        ],
      },
    ],
  },
  {
    name: '3rd Year 2025-26 (6th Sem)',
    description: 'Academic sheets for 6th semester including TLC sheets, student section details, mentor structure, and LeetCode trackers.',
    icon: 'BookOpen',
    color: 'blue',
    category: 'Academic',
    order: 1,
    items: [
      {
        name: 'Student Details & Mentor Structure',
        description: '3rd year all section student lists, 3H section details, and main/support mentor allocation.',
        resourceUrl: 'https://docs.google.com/spreadsheets/d/1ERMFJ2rdtkuHlQgQtBxlRq2YFWtB11iU0haHvqkOhtI/edit?gid=0#gid=0',
        order: 0,
        resources: [
          {
            name: '3rd All sections Student Details',
            description: 'Master list of all 3rd year student sections',
            url: 'https://docs.google.com/spreadsheets/d/1ERMFJ2rdtkuHlQgQtBxlRq2YFWtB11iU0haHvqkOhtI/edit?gid=0#gid=0',
            emailsUsed: [],
          },
          {
            name: '3H Student Details',
            description: '3H section student details sheet',
            url: 'https://docs.google.com/spreadsheets/d/1NuUXROvrSiK-b1ACVy6tcOh5ojvQejD4EZCuXd8-z9o/edit?pli=1&gid=804975247#gid=804975247',
            emailsUsed: [],
          },
          {
            name: 'Main-Support -Mentor Structure',
            description: 'Mentor assignment & support hierarchy sheet',
            url: 'https://docs.google.com/spreadsheets/d/1ItBgk9LoBaHYCd-WvQ39DL1hY6v9zcqy0jBxNTZbGOc/edit?pli=1&gid=44682391#gid=44682391',
            emailsUsed: [],
          },
          {
            name: 'Support Mentors',
            description: 'Support mentor roster & details',
            url: 'https://docs.google.com/spreadsheets/d/1flDaiUNhwnViWCZRxNUhf6NsdJ8WP65R_I5ObICXGDA/edit?pli=1&gid=1378998238#gid=1378998238',
            emailsUsed: [],
          },
        ],
      },
      {
        name: 'TLC & Course Trackers (5th & 6th Sem)',
        description: 'TLC progress sheets, LDP section-wise trackers, weekly summaries, and extra concepts logs.',
        resourceUrl: 'https://docs.google.com/spreadsheets/d/1t324SUjBwbR6wEamEiinNErjSkudaeRFXJm1cTqfSJM/edit?pli=1&gid=2000864649#gid=2000864649',
        order: 1,
        resources: [
          {
            name: 'GLA 3rd Year (6th Sem) TLC Sheet',
            description: '6th Semester TLC tracking sheet',
            url: 'https://docs.google.com/spreadsheets/d/1t324SUjBwbR6wEamEiinNErjSkudaeRFXJm1cTqfSJM/edit?pli=1&gid=2000864649#gid=2000864649',
            emailsUsed: [],
          },
          {
            name: 'Copy of GLA 3rd Year (6th Sem) TLC Sheet',
            description: 'Backup 6th Sem TLC tracker',
            url: 'https://docs.google.com/spreadsheets/d/161xUuIdrhL_J3Aj5xJGpx51qxKy1GrekywmLfN5vN8s/edit?pli=1&gid=961286731#gid=961286731',
            emailsUsed: [],
          },
          {
            name: 'GLA 3rd Year (5th Sem) TLC Sheet',
            description: '5th Semester TLC tracking sheet',
            url: 'https://docs.google.com/spreadsheets/d/1JZsatC7Q8uek8bwMbMAvyeN7Zl4YpwxyikzHZkrpU8s/edit?pli=1&gid=829634347#gid=829634347',
            emailsUsed: [],
          },
          {
            name: '2. GLA 2026 LDP Tracker - Section wise',
            description: 'Section wise LDP progress tracker',
            url: 'https://docs.google.com/spreadsheets/d/1FbbiJ4jIa2U7DZsggEff_T-AWgo1M7M6GV0Xt60GfIY/edit?pli=1&gid=716019329#gid=716019329',
            emailsUsed: [],
          },
          {
            name: 'Week Summary of LDP',
            description: 'Weekly LDP execution summary',
            url: 'https://docs.google.com/spreadsheets/d/1LccUwo0iZetjg_MYTwjodQmPJHLlTlLXV7i5JnC4xh4/edit?pli=1&gid=0#gid=0',
            emailsUsed: [],
          },
          {
            name: 'Extra-concepts-covered',
            description: 'Log of additional concepts covered during sessions',
            url: 'https://docs.google.com/spreadsheets/d/1QRV6kQkmAQF4Hh6u5FfIdwlpWJAiR7cLI9BXgpVUNOg/edit?pli=1&gid=839447992#gid=839447992',
            emailsUsed: [],
          },
          {
            name: 'Unmapped-Hours',
            description: 'Tracking unmapped session hours',
            url: 'https://docs.google.com/spreadsheets/d/1GI_jcAWX1oplLiTHBV70q_ETHfChaae7qGx4hez0v68/edit?pli=1&gid=1704001682#gid=1704001682',
            emailsUsed: [],
          },
        ],
      },
      {
        name: 'LeetCode & DSA Trackers (6th Sem)',
        description: '6th Sem LeetCode tracker, DSA problem sets, and submission forms/responses.',
        resourceUrl: 'https://docs.google.com/spreadsheets/d/1Ryce7FsaPq4xRi3r83dFA9iNp97EAJeElHSCVz4-sL4/edit?gid=0#gid=0',
        order: 2,
        resources: [
          {
            name: '3rd Year (6th Sem) - Leetcode Tracker',
            description: '6th Sem LeetCode solved problems tracker',
            url: 'https://docs.google.com/spreadsheets/d/1Ryce7FsaPq4xRi3r83dFA9iNp97EAJeElHSCVz4-sL4/edit?gid=0#gid=0',
            emailsUsed: [],
          },
          {
            name: '3rd Yr DSA Problems',
            description: 'Curated 3rd year DSA practice problem set',
            url: 'https://docs.google.com/spreadsheets/d/1r66vntpKio5CG7ZvKcrePrCvSgOSS-X4ViuzW7yxt5A/edit?gid=1089193982#gid=1089193982',
            emailsUsed: [],
          },
          {
            name: 'Leetcode Details 6th sem (Responses)',
            description: 'Student LeetCode submissions responses sheet',
            url: 'https://docs.google.com/spreadsheets/d/11ZyixjSU3v2oSCs-iM4kg3qmPWutazAxWGJYvOm93-s/edit?resourcekey=&gid=1530466725#gid=1530466725',
            emailsUsed: [],
          },
          {
            name: 'Leetcode Detail (Responses)',
            description: 'Additional LeetCode details responses sheet',
            url: 'https://docs.google.com/spreadsheets/d/12z6kKsXH5RF4ZdKoCUdEUA-8rOUlfwIt-OQZzT0-yAU/edit?resourcekey=&gid=354818424#gid=354818424',
            emailsUsed: [],
          },
          {
            name: 'Leetcode details (Google Form)',
            description: 'Submission Google Form for LeetCode profiles',
            url: 'https://docs.google.com/forms/d/e/1FAIpQLSetMn0vLqTfL6O1w2xC6k6N1IUuIwJaofBfQJlD0DQMWl4ylQ/viewform',
            emailsUsed: [],
          },
        ],
      },
      {
        name: 'Timetables & Issue Trackers (6th Sem)',
        description: '6th sem timetable, daily issue trackers, and classroom member lists.',
        resourceUrl: 'https://docs.google.com/spreadsheets/d/1KROB9VOW_0Ymg-Mh_0gSgm_PDvO2VYa_BxeCZlE7Rjw/edit?pli=1&gid=0#gid=0',
        order: 3,
        resources: [
          {
            name: '3rd yr timetable',
            description: '3rd year 6th sem class timetable',
            url: 'https://docs.google.com/spreadsheets/d/1KROB9VOW_0Ymg-Mh_0gSgm_PDvO2VYa_BxeCZlE7Rjw/edit?pli=1&gid=0#gid=0',
            emailsUsed: [],
          },
          {
            name: 'Even Sem Daily Issue Tracker',
            description: 'Daily operational issue log for even sem',
            url: 'https://docs.google.com/spreadsheets/d/14vcGn_tZNz1b9_EVbdD1HusnZ5E8UqlcehEUuz1kl_0/edit?pli=1&gid=0#gid=0',
            emailsUsed: [],
          },
          {
            name: 'Overall - Issue Tracker (6th Sem)',
            description: 'Centralized issue tracker sheet',
            url: 'https://docs.google.com/spreadsheets/d/1akxk0w-KbnGm-FDc7yumR7WHNZSiwWrVdsLUI-WneAg/edit?gid=1038960680#gid=1038960680',
            emailsUsed: [],
          },
          {
            name: 'Classroom People Roster',
            description: 'Google Classroom student & teacher roster',
            url: 'https://classroom.google.com/r/NzkxMTIyNDQ5NzY5/sort-first-name',
            emailsUsed: [],
          },
        ],
      },
    ],
  },
  {
    name: '3Y 2025-26 Exam Data',
    description: 'Node.js FullStack Lab exams, theory marks, internal/external evaluations, and mini-project synopsis.',
    icon: 'FileCheck',
    color: 'purple',
    category: 'Academic',
    order: 2,
    items: [
      {
        name: 'FullStack Node.js Lab & Theory Evaluation',
        description: 'Node.js FullStack lab exam submissions, theory marks, and internal/external evaluation sheets.',
        resourceUrl: 'https://docs.google.com/spreadsheets/d/1XyIUxkr3SRrJve84ho5R_b5KaDd63M8dibqeaGJfopA/edit?gid=1617836678#gid=1617836678',
        order: 0,
        resources: [
          {
            name: 'BCSE0282_FullStack_NodeJS_LabExam_Submission',
            description: 'FullStack Node.js Lab Exam student submissions',
            url: 'https://docs.google.com/spreadsheets/d/1XyIUxkr3SRrJve84ho5R_b5KaDd63M8dibqeaGJfopA/edit?gid=1617836678#gid=1617836678',
            emailsUsed: [],
          },
          {
            name: 'BCSE0252_FullStack_NodeJS_TheoryMarks',
            description: 'Node.js Theory marks evaluation sheet',
            url: 'https://docs.google.com/spreadsheets/d/1n0kABYknC3ii0Ha62zxiRdiNxBY1lQ6yG8ZuXWR9xmE/edit?gid=1628610256#gid=1628610256',
            emailsUsed: [],
          },
          {
            name: 'BCSE0282_LabMarks_Internal_External',
            description: 'Internal & External lab marks consolidation',
            url: 'https://docs.google.com/spreadsheets/d/1y8eevjLpmbm2QypcoJuFRKbifqCmwGNKqz4ZgCRhD_A/edit?gid=1017482679#gid=1017482679',
            emailsUsed: [],
          },
          {
            name: 'Lab Practical Submission (Responses)',
            description: 'Responses spreadsheet for lab practical submissions',
            url: 'https://docs.google.com/spreadsheets/d/15-c0Gv6EZRD7EsxCVVxrutZXAopahiUfgPTTdtE_0h8/edit?resourcekey=&gid=1490750133#gid=1490750133',
            emailsUsed: [],
          },
          {
            name: 'Lab Practical Submission (Google Form)',
            description: 'Google Form for lab practical submission',
            url: 'https://docs.google.com/forms/d/1Hl-OcIAJp2DQAjuBIK8X2Ee0Igz1Xd62YKMg_2QePTw/edit',
            emailsUsed: [],
          },
        ],
      },
      {
        name: 'Mini Project Synopsis & Final Evaluation 2026',
        description: 'Mini Project group formations, synopsis submissions, final evaluation sheets, and file upload drive folders.',
        resourceUrl: 'https://docs.google.com/spreadsheets/d/16SCf--006W0ORR_8HYG2fEoGMVCGzZmV6mjTtaVV2Lc/edit?gid=613283876#gid=613283876',
        order: 1,
        resources: [
          {
            name: 'Mini Project Group Formation',
            description: 'Group formation & team allocation spreadsheet',
            url: 'https://docs.google.com/spreadsheets/d/16SCf--006W0ORR_8HYG2fEoGMVCGzZmV6mjTtaVV2Lc/edit?gid=613283876#gid=613283876',
            emailsUsed: [],
          },
          {
            name: 'Mini Project Final Evaluation_2026',
            description: 'Final evaluation & grading sheet for 2026 mini projects',
            url: 'https://docs.google.com/spreadsheets/d/12xwRElHW1Z9UAZ1hFzuECqNKSZQ8lUNM27ndRTziTd8/edit?gid=1194978215#gid=1194978215',
            emailsUsed: [],
          },
          {
            name: 'Mini Project Synopsis Responses (Spreadsheet)',
            description: 'Consolidated synopsis responses sheet',
            url: 'https://docs.google.com/spreadsheets/d/1coCyxNet72HaS1MH2uoWzW8BgPnBmgHhjp7GFGKZYrE/edit?resourcekey=&gid=161011690#gid=161011690',
            emailsUsed: [],
          },
          {
            name: 'Mini Project Synopsis Responses (Drive Sheet)',
            description: 'Synopsis responses in Google Drive',
            url: 'https://docs.google.com/spreadsheets/d/1coCyxNet72HaS1MH2uoWzW8BgPnBmgHhjp7GFGKZYrE/edit?resourcekey=&gid=2021670920#gid=2021670920',
            emailsUsed: [],
          },
          {
            name: 'Mini Project Synopsis Submission – 2026 (Google Form)',
            description: 'Google Form for 2026 mini project synopsis submission',
            url: 'https://docs.google.com/forms/d/1BO0K5IIK2_NAlxaZdUcCyFM_cHDd3ks39HaEXc7_TUs/edit#responses',
            emailsUsed: [],
          },
          {
            name: 'Upload Mini Project Synopsis (File Responses Drive Folder)',
            description: 'Google Drive folder containing submitted synopsis PDF files',
            url: 'https://drive.google.com/drive/folders/15aCJF6j1Sf3phjcoeHXgsyT682f753ZY43QikXRT2gMgYacSd0sX6oi6NZYdRpIrPT8oJ1tf',
            emailsUsed: [],
          },
          {
            name: 'Online Code Collaborator GitHub Repo',
            description: 'Sample online code collaborator project repository',
            url: 'https://github.com/TusharBhardwaj47/online-code-collaborator/tree/dev',
            emailsUsed: [],
          },
        ],
      },
    ],
  },
  {
    name: 'BridgeLabz Operations',
    description: 'PTT tracking, overall issue logs, and brandquest sheets.',
    icon: 'FolderKanban',
    color: 'cyan',
    category: 'Sheets',
    order: 3,
    items: [
      {
        name: 'PTT & Issue Trackers',
        description: 'Current PTT sheet and centralized issue resolution log.',
        resourceUrl: 'https://docs.google.com/spreadsheets/d/1K9xpswVgxouwyi2psa22hjt0YhEtgcTS_mf0A2lzSEc/edit?gid=53021516#gid=53021516',
        order: 0,
        resources: [
          {
            name: 'BL Current PTT',
            description: 'BridgeLabz PTT tracking sheet',
            url: 'https://docs.google.com/spreadsheets/d/1K9xpswVgxouwyi2psa22hjt0YhEtgcTS_mf0A2lzSEc/edit?gid=53021516#gid=53021516',
            emailsUsed: [],
          },
          {
            name: 'Overall - Issue Tracker',
            description: 'Cross-functional issue tracking sheet',
            url: 'https://docs.google.com/spreadsheets/d/1akxk0w-KbnGm-FDc7yumR7WHNZSiwWrVdsLUI-WneAg/edit?gid=1038960680#gid=1038960680',
            emailsUsed: [],
          },
          {
            name: 'Capgemini-brandquest',
            description: 'Brandquest project spreadsheet',
            url: 'https://docs.google.com/spreadsheets/d/1mF5yViHs_Ya4rOJ2nBMB3sdWqNK1cfrwl79FoVxx2vE/edit?gid=748947375#gid=748947375',
            emailsUsed: [],
          },
        ],
      },
    ],
  },
  {
    name: 'BL Projects',
    description: 'BridgeLabz AI Platforms & Cloud Run services across Dev, QA, and Staging clusters.',
    icon: 'Bot',
    color: 'indigo',
    category: 'Projects',
    order: 4,
    items: [
      {
        name: 'Review AI',
        description: 'Automated code review & feedback generation system.',
        githubUrl: 'https://github.com/bl-org/review-ai',
        order: 0,
        resources: [
          {
            name: 'ReviewAI WebApp (Staging)',
            description: 'Frontend Staging Endpoint',
            url: 'https://ejet-review-ai-webapp-staging-187791816934.asia-south1.run.app',
            emailsUsed: ['admin@bridgelabz.com', 'developer@bridgelabz.com'],
          },
          {
            name: 'ReviewAI WebApp (QA)',
            description: 'Frontend QA Endpoint for testing',
            url: 'https://ejet-review-ai-webapp-qa-187791816934.asia-south1.run.app',
            emailsUsed: ['qa@bridgelabz.com'],
          },
          {
            name: 'ReviewAI Backend (QA AI Engine)',
            description: 'Python AI inference engine on QA',
            url: 'https://ejet-reviewai-backend-qa-187791816934.asia-south1.run.app',
            emailsUsed: ['admin@bridgelabz.com'],
          },
        ],
      },
      {
        name: 'Content AI',
        description: 'Multi-modal generation & copywriting workflow engine.',
        githubUrl: 'https://github.com/bl-org/content-ai',
        order: 1,
        resources: [
          {
            name: 'ContentAI WebApp (Staging)',
            description: 'Frontend Staging Endpoint',
            url: 'https://ejet-content-ai-webapp-staging-187791816934.asia-south1.run.app',
            emailsUsed: ['admin@bridgelabz.com'],
          },
          {
            name: 'ContentAI WebApp (QA)',
            description: 'Frontend QA Endpoint',
            url: 'https://ejet-content-ai-webapp-qa-187791816934.asia-south1.run.app',
            emailsUsed: ['qa@bridgelabz.com'],
          },
        ],
      },
      {
        name: 'Practice AI',
        description: 'Interactive developer sandbox for prompt engineering.',
        githubUrl: 'https://github.com/bl-org/practice-ai',
        order: 2,
        resources: [
          {
            name: 'PracticeAI WebApp (Staging)',
            description: 'Staging Cloud Run UI',
            url: 'https://ejet-practice-ai-webapp-staging-187791816934.asia-south1.run.app',
            emailsUsed: ['dev@bridgelabz.com'],
          },
        ],
      },
    ],
  },
];
